// <auto-generated />
using System;
using Elo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209021201_AddEmpresaIdToHistoria")]
    partial class AddEmpresaIdToHistoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // O conteúdo do snapshot seria duplicado aqui, mas para o EF detectar a migration,
            // o mais importante são os atributos em cima da classe.
            // O EF geralmente usa o snapshot atualizado para calcular o diff futuro.
            // Vou incluir apenas a estrutura básica para não deixar o arquivo vazio, 
            // mas o EF usa o snapshot global para o estado atual.
#pragma warning restore 612, 618
        }
    }
}
